[2024-04-03T03:22:15.499+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.load_data_to_bigquery manual__2024-04-03T03:21:58.097532+00:00 [queued]>
[2024-04-03T03:22:15.512+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.load_data_to_bigquery manual__2024-04-03T03:21:58.097532+00:00 [queued]>
[2024-04-03T03:22:15.513+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-03T03:22:15.538+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_bigquery> on 2024-04-03 03:21:58.097532+00:00
[2024-04-03T03:22:15.545+0000] {standard_task_runner.py:60} INFO - Started process 5595 to run task
[2024-04-03T03:22:15.550+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_sheet_to_bigquery', 'load_data_to_bigquery', 'manual__2024-04-03T03:21:58.097532+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dags/habidag.py', '--cfg-path', '/tmp/tmp1yw7wxu4']
[2024-04-03T03:22:15.551+0000] {standard_task_runner.py:88} INFO - Job 85: Subtask load_data_to_bigquery
[2024-04-03T03:22:15.611+0000] {task_command.py:423} INFO - Running <TaskInstance: google_sheet_to_bigquery.load_data_to_bigquery manual__2024-04-03T03:21:58.097532+00:00 [running]> on host 84784c125ee0
[2024-04-03T03:22:15.713+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_sheet_to_bigquery' AIRFLOW_CTX_TASK_ID='load_data_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T03:21:58.097532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T03:21:58.097532+00:00'
[2024-04-03T03:22:15.736+0000] {logging_mixin.py:188} INFO -    idTransportista     nombreEmpresa
0                1    Speedy Express
1                2    United Package
2                3  Federal Shipping
3                4     test cargue 1
[2024-04-03T03:22:15.738+0000] {logging_mixin.py:188} INFO - INSERT `papyrus-technical-test.datalake_anyeli.transportistas` VALUES (1, Speedy Express), (2, United Package), (3, Federal Shipping), (4, test cargue 1);
[2024-04-03T03:22:15.749+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-03T03:22:15.754+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-04-03T03:22:15.820+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': 'INSERT `papyrus-technical-test.datalake_anyeli.transportistas` VALUES (1, Speedy Express), (2, United Package), (3, Federal Shipping), (4, test cargue 1);', 'useLegacySql': False, 'priority': 'BATCH'}}'
[2024-04-03T03:22:15.822+0000] {bigquery.py:1613} INFO - Inserting job ***_adhoc_***_insert_data_2024_04_03T03_21_58_097532_00_00_fd98c35dc8744de42d520230d2f067c4
[2024-04-03T03:22:16.550+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags/habidag.py", line 49, in load_data_to_bigquery
    insert_query_job.execute(kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2870, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected ")" or "," but got identifier "Express" at [1:82]; reason: invalidQuery, location: query, message: Syntax error: Expected ")" or "," but got identifier "Express" at [1:82]

Location: US
Job ID: airflow_adhoc_airflow_insert_data_2024_04_03T03_21_58_097532_00_00_fd98c35dc8744de42d520230d2f067c4

[2024-04-03T03:22:16.580+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=google_sheet_to_bigquery, task_id=load_data_to_bigquery, execution_date=20240403T032158, start_date=20240403T032215, end_date=20240403T032216
[2024-04-03T03:22:16.603+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task load_data_to_bigquery (400 Syntax error: Expected ")" or "," but got identifier "Express" at [1:82]; reason: invalidQuery, location: query, message: Syntax error: Expected ")" or "," but got identifier "Express" at [1:82]

Location: US
Job ID: airflow_adhoc_airflow_insert_data_2024_04_03T03_21_58_097532_00_00_fd98c35dc8744de42d520230d2f067c4
; 5595)
[2024-04-03T03:22:16.647+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-03T03:22:16.667+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
